### ISSUE TITLE
error: Failed to parse PDF document (line:200 col:144 offset=774016): Failed to parse invalid PDF object

### ISSUE THREAD

**Issue by deathemperor** [cantoo-scribe/pdf-lib#63]
### What were you trying to do?

Load PDF

### How did you attempt to do it?

```ts
import { PDFDocument } from "@cantoo/pdf-lib";

const doc = await PDFDocument.load(
  await fetch("https://care.cdn.papaya.services/docs/ca06ea12-517b-46e2-b3d5-554966536937/y0j2NRDLuw_InvoicePaper_1715784300908.pdf?key=23").then(res => res.arrayBuffer()),
);
```

### What actually happened?

```log
123 | }
124 | export class PDFParsingError extends Error {
125 |     constructor(pos, details) {
126 |         const msg = `Failed to parse PDF document ` +
127 |             `(line:${pos.line} col:${pos.column} offset=${pos.offset}): ${details}`;
128 |         super(msg);
              ^
error: Failed to parse PDF document (line:200 col:144 offset=774016): Failed to parse invalid PDF object
      at new PDFParsingError (/Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/errors.js:128:9)
      at new PDFInvalidObjectParsingError (/Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/errors.js:146:9)
      at tryToParseInvalidIndirectObject (/Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/parser/PDFParser.js:151:19)
      at /Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/parser/PDFParser.js:167:22
```

### What did you expect to happen?

Able to load pdf

### How can we reproduce the issue?

```ts
import { PDFDocument } from "@cantoo/pdf-lib";

const doc = await PDFDocument.load(
  await fetch("https://care.cdn.papaya.services/docs/ca06ea12-517b-46e2-b3d5-554966536937/y0j2NRDLuw_InvoicePaper_1715784300908.pdf?key=23").then(res => res.arrayBuffer()),
);
```

### Version

2.2.3

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by Sharcoux** [comment]
If someone is willing to have a look. I'm afraid we won't have time before next month.

**Comment by Sharcoux** [comment]
Can you try v2.8.1 see if you still have the issue?

**Comment by deathemperor** [comment]
Still reproduces on v2.8.1 — unlike #64, which the 2.8.1 xref guard did fix.

The CDN host changed since I filed this, so the URL in the original report 404s. Working link for the same file:

https://care.cdn.services.papaya.asia/docs/ca06ea12-517b-46e2-b3d5-554966536937/y0j2NRDLuw_InvoicePaper_1715784300908.pdf?key=23

| version | outcome |
|---|---|
| 2.2.3 | `PDFInvalidObjectParsingError: Failed to parse PDF document (line:200 col:144 offset=774016)` at `PDFParser.js:151` |
| 2.8.1 | identical error, at `PDFParser.js:160` |

**Root cause:** the file is truncated. It is 774144 B (exactly 756 KiB — a clean transfer-truncation boundary) and ends mid-object:

```
28 0 obj
<</BaseFont/CAAAAA+NotoSerif-Italic/CIDSystemInfo<</Ordering(Identity)…/CIDToGIDMap/Iden
```

No `endobj`, no xref, no trailer, no `%%EOF`. Object 28 begins at offset 774016 — exactly where the parser throws. So the PDF really is damaged, and I'd have no complaint if the answer is "garbage in".

**But the rest of the document is intact and recoverable.** Chopping off just the incomplete trailing object:

```console
$ head -c 774016 real63.pdf > trimmed.pdf
```

```
trimmed: OK pages=2
trimmed: re-saved 772681B
```

So pdf-lib can already reconstruct this file — `maybeRecoverRoot()` finds the catalog without any xref. The only thing standing between the current behaviour and a successfully loaded 2-page document is the last line of `tryToParseInvalidIndirectObject`:

```js
if (failed)
    throw new PDFInvalidObjectParsingError(startPos);
```

Two things look off there, independent of my file:

1. **The throw is unconditional.** It fires even with the default `throwOnInvalidObject: false`. The `throwOnInvalidObject` / `warnOnInvalidObjects` checks at the top of that same function suggest the intent was for this path to be lenient by default.
2. **`failed` here specifically means "hit EOF"**, since the scan loop only exits via `bytes.done()` or a matched `endobj`. A trailing fragment at EOF is the one case where discarding it costs nothing — every complete object before it has already been assigned to the context.

Proposed fix: when the scan reaches EOF without an `endobj`, discard the trailing fragment (warn under `warnOnInvalidObjects`) and let parsing finish, throwing only when `throwOnInvalidObject` is set. Truncated-download PDFs are common enough that recovering the readable prefix seems worth it, and it matches how the parser already treats every other malformed-object case.

Happy to open that PR with regression tests covering both this and the #64 xref case — just say the word.

**Comment by deathemperor** [comment]
Opened #146 with the fix and regression tests for both this and #64.
