### ISSUE TITLE
error: Failed to parse number (line:10321 col:8 offset=462848): ""

### ISSUE THREAD

**Issue by deathemperor** [cantoo-scribe/pdf-lib#64]
### What were you trying to do?

Load pdf

### How did you attempt to do it?

```ts
const doc2 = await PDFDocument.load(
  await fetch("https://care.cdn.papaya.services/docs/97a9f74e-1e84-4cce-9540-6b65605d2bb9/QWHyicZLjE_InvoicePaper_1715478056267.pdf?key=23").then(res => res.arrayBuffer()),
);

console.log(doc2);
```

### What actually happened?

```log
116 | }
117 | export class NumberParsingError extends Error {
118 |     constructor(pos, value) {
119 |         const msg = `Failed to parse number ` +
120 |             `(line:${pos.line} col:${pos.column} offset=${pos.offset}): "${value}"`;
121 |         super(msg);
              ^
error: Failed to parse number (line:10321 col:8 offset=462848): ""
      at new NumberParsingError (/Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/errors.js:121:9)
      at parseRawInt (/Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/parser/BaseParser.js:23:19)
      at maybeParseCrossRefSection (/Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/parser/PDFParser.js:186:36)
      at /Users/deathemperor/papaya/berry/node_modules/@cantoo/pdf-lib/es/core/parser/PDFParser.js:236:14
```

### What did you expect to happen?

Able to load pdf

### How can we reproduce the issue?

```ts
const doc2 = await PDFDocument.load(
  await fetch("https://care.cdn.papaya.services/docs/97a9f74e-1e84-4cce-9540-6b65605d2bb9/QWHyicZLjE_InvoicePaper_1715478056267.pdf?key=23").then(res => res.arrayBuffer()),
);

console.log(doc2);

```

### Version

2.2.3

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by Sharcoux** [comment]
Looks like a duplicate of https://github.com/cantoo-scribe/pdf-lib/issues/63

I'll close if no justification for a second issue is provided

**Comment by Sharcoux** [comment]
My bad actually

**Comment by Sharcoux** [comment]
Can you check if it is still valid in v2.8.1 ?

**Comment by deathemperor** [comment]
Confirmed **fixed** in v2.8.1.

The CDN host changed since I filed this, so the URL in the original report 404s. Working link for the same file:

https://care.cdn.services.papaya.asia/docs/97a9f74e-1e84-4cce-9540-6b65605d2bb9/QWHyicZLjE_InvoicePaper_1715478056267.pdf?key=23

Re-ran the original repro against both versions:

| version | outcome |
|---|---|
| 2.2.3 | `NumberParsingError: Failed to parse number (line:10321 col:8 offset=462848): ""` — byte-identical to the original report |
| 2.8.1 | loads fine, `getPageCount() === 8`, re-saves to 459813 B |

Note `offset=462848` is exactly the file length, i.e. 2.2.3 ran off the end of the buffer parsing the xref section. That's what the guard added in 2.8.1 catches:

```js
// Check if second digit is valid integer
if (!IsDigit[this.bytes.peek()]) {
    return PDFCrossRefSection.createEmpty();
}
const secondInt = this.parseRawInt();
```

Good to close. Thanks for picking these back up.
