### ISSUE TITLE
Error while creating a deep clone of encrypted PDFDocument object.

### ISSUE THREAD

**Issue by Talha345** [cantoo-scribe/pdf-lib#65]
### What were you trying to do?

I create a deep clone of the PDFDocument object before applying any changes to it using the following code: 

`const copiedPdfDoc = await PDFDocument.load(await pdfDoc.save());`

This approach has been working reliably for a long time, but after switching to the new fork, I've encountered a problem with certain encrypted PDF files that have been decrypted. For most files, the deep clone works fine. However, when dealing with specific decrypted PDFs, the `PDFDocument.catalog` in the cloned document is set to `PDFInvalidObject` instead of the expected `PDFCatalog` and when I try to do `await copiedPdfDoc.save();`, I get the following error:

```
TypeError: this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] 
    at Cache.access (Cache.js:11:1)
    at PDFDocument.getPages (PDFDocument.js:478:1)
    at PDFDocument.getPageCount (PDFDocument.js:462:1)
    at PDFDocument.save (PDFDocument.js:1147:1)
```

Document for which the issue occurs:

[g-1145.pdf](https://github.com/user-attachments/files/16731678/g-1145.pdf)

### How did you attempt to do it?

1. Load the provided PDF document.
2. Create a deep clone of the document using the code provided above.
3. Try to save the copied pdf document. 

### What actually happened?

```
TypeError: this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] 
    at Cache.access (Cache.js:11:1)
    at PDFDocument.getPages (PDFDocument.js:478:1)
    at PDFDocument.getPageCount (PDFDocument.js:462:1)
    at PDFDocument.save (PDFDocument.js:1147:1)
```

### What did you expect to happen?

The PDF to be saved properly.

### How can we reproduce the issue?

Use the steps above.

### Version

2.2.3

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by Talha345** [comment]
Update: I migrated the decryption logic to use qpdf and it works like a charm but it would be nice if pdf-lib handles this correctly.

**Comment by Sharcoux** [comment]
We might try to have a look, but I'm really not sure we can help on this. I'll mark this as help wanted.

**Comment by Sharcoux** [comment]
Can you check if v2.8.1 solves it?
