### ISSUE TITLE
Error embeding png

### ISSUE THREAD

**Issue by deathemperor** [cantoo-scribe/pdf-lib#72]
### What were you trying to do?

Embed png file into page

### How did you attempt to do it?

```ts
const pdf = await PDFDocument.create();
const image = await pdf.embedPng(file);
const page = pdf.addPage([image.width, image.height]);
```

file is buffer, attached

![bc891fa0-9cef-4165-89b3-02356b97b5a5](https://github.com/user-attachments/assets/c71622ee-c5d2-40f4-a0f5-7635b3aa77ef)

### What actually happened?

2024-10-17 01:54:06.455	ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"dV.default.decode is not a function","stack":["TypeError: dV.default.decode is not a function","    at new PNG (/node_modules/@cantoo/pdf-lib/src/utils/png.ts:51:23)","    at pngData (/node_modules/@cantoo/pdf-lib/src/utils/png.ts:41:42)","    at Function.for (/node_modules/@cantoo/pdf-lib/src/core/embedders/PngEmbedder.ts:12:21)","    at a.embedPng (/node_modules/@cantoo/pdf-lib/src/api/PDFDocument.ts:1113:40)"

### What did you expect to happen?

added successfully

### How can we reproduce the issue?

```ts
const pdf = await PDFDocument.create();
const image = await pdf.embedPng(file);
const page = pdf.addPage([image.width, image.height]);
```

file is buffer, attached

### Version

2.2.3

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by deathemperor** [comment]
strangely enough it doesn't happen running with bun, only nodejs (v20, v22)

**Comment by deathemperor** [comment]
original pdf-lib doesn't encounter this issue FYI

**Comment by deathemperor** [comment]
> Which version of Node did you use?

happens on node 18, 20, and 22

**Comment by benconnito** [comment]
looks to be happening when using esm ...

```
import UPNG from '@pdf-lib/upng';
```

is an object with `default`

![image](https://github.com/user-attachments/assets/2315bed1-dba3-4b06-b048-40f407972afa)

**Comment by Sharcoux** [comment]
It seems like it was due to a typo in the code for esm. I'll fix and release.

**Comment by Sharcoux** [comment]
To solve the issue, we would probably need to solve this problem:

https://github.com/cantoo-scribe/pdf-lib/issues/24

**Comment by sameer-roofr** [comment]
@deathemperor  did you find a solution to this issue?

**Comment by deathemperor** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/4255482?u=4acd6d9af47c210ac94e8f57427ad20159940d4a&amp;v=4&amp;size=80">@deathemperor](https://github.com/deathemperor?rgh-link-date=2025-01-17T16%3A17%3A30.000Z) did you find a solution to this issue?

I used original pdf-lib and other stuffs I use this lib

**Comment by Sharcoux** [comment]
Can you check if v2.8.1 solves this issue?

**Comment by deathemperor** [comment]
Yes — fixed, and I can reproduce both sides with the PNG attached to this issue.

The cause is ESM/CJS interop on `@pdf-lib/upng`. That package's CJS entry exports `{ __esModule: true, default: { decode, toRGBA8, ... } }`, so the `import UPNG from '@pdf-lib/upng'` default binding resolves to the namespace object rather than to UPNG itself, and `UPNG.decode` is undefined. Your bundler had minified `UPNG` to `dV.default`, which is why the message read `dV.default.decode is not a function`.

Tested against the attached file on Node 25:

| | 2.2.3 | 2.8.1 |
|---|---|---|
| CJS (`require`) | works | works |
| ESM (`import`) | `TypeError: UPNG.decode is not a function` | works |

On 2.8.1 both paths embed the image and produce a 2,146,358 B PDF at 1920×2715. That also explains why this only bit you in Lambda — plain CJS `require` was never affected, only the ESM/bundled path.

The fix is e0864842 ("Handle correct support for '@pdf-lib/upng' CJS / ESM"), which picks whichever of `UPNG` / `UPNG.default` actually carries `decode`. It first shipped in **v2.4.5**, so any release from there on works. A follow-up, d2fa9e31 (v2.7.1), additionally handles non-`ArrayBuffer` inputs into `UPNGmod.decode` — relevant here since you pass a Node `Buffer`, whose `.buffer` is a pooled `ArrayBuffer` that's usually larger than the view.

So 2.8.1 covers both. Safe to close.

**Comment by Sharcoux** [comment]
That's a very clear explanation. Thanks.
